Categorias:
    type: entity
    table: categorias
    indexes:
        fk_CategoriasTiposCategoriaId_TipoCategoriasTipoCategoriaId:
            columns:
                - TipoCategoriaId
    id:
        categoriaid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: Categoriaid
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: Nombre
        vigente:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: Vigente
        eliminado:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: Eliminado
        fecha:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: Fecha
    manyToOne:
        tipocategoriaid:
            targetEntity: Tipocategorias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TipoCategoriaId:
                    referencedColumnName: TipoCategoriaId
            orphanRemoval: false
    lifecycleCallbacks: {  }
