Extensiones:
    type: entity
    table: extensiones
    indexes:
        fk_ExtensionesTipoArchivoId_TipoArchivosTipoArchivoId:
            columns:
                - TipoArchivoId
    id:
        extensionid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ExtensionId
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: Nombre
        vigente:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: Vigente
        eliminado:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: Eliminado
        fecha:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: Fecha
    manyToOne:
        tipoarchivoid:
            targetEntity: Tipoarchivos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TipoArchivoId:
                    referencedColumnName: TipoArchivoId
            orphanRemoval: false
    lifecycleCallbacks: {  }
