Relacionusuarioprivilegio:
    type: entity
    table: relacionusuarioprivilegio
    indexes:
        fk_RelacionUsuarioPrivilegioUsuarioId_UsuariosUsuarioId:
            columns:
                - UsuarioId
        fk_RelacionUsuarioPrivilegioPrivilegioId_PrivilegiosPrivilegioId:
            columns:
                - PrivilegioId
    id:
        usuarioprivilegioid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: UsuarioPrivilegioId
            generator:
                strategy: IDENTITY
    fields:
        vigente:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: Vigente
        eliminado:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: Eliminado
        fecha:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: Fecha
    manyToOne:
        privilegioid:
            targetEntity: Privilegios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PrivilegioId:
                    referencedColumnName: PrivilegioId
            orphanRemoval: false
        usuarioid:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                UsuarioId:
                    referencedColumnName: UsuarioId
            orphanRemoval: false
    lifecycleCallbacks: {  }
